#____________________________________________________________________________________________
# set_accj_rt
#____________________________________________________________________________________________
float32[6] acc
---
bool       success
