#____________________________________________________________________________________________
# set_velx_rt
#____________________________________________________________________________________________
float32    trans
float32    rotation
---
bool       success
