#____________________________________________________________________________________________
# set_velj_rt
#____________________________________________________________________________________________
float32[6] vel
---
bool       success
