#____________________________________________________________________________________________
# alter_motion  
# 
#____________________________________________________________________________________________

float32[6] pos               # position  
---
bool success
