#____________________________________________________________________________________________
# get_workpiece_weight
#____________________________________________________________________________________________

---
float64       weight               # Measured weight, Negative value if error
bool          success
