#____________________________________________________________________________________________
# config_create_tool 
# It is a service for registering and using robot Tool information in advance for safety 
#____________________________________________________________________________________________

string          name        # tool name 
float32         weight      # tool weight 
float32[3]      cog         # Center of gravity
float32[6]      inertia     # tool inertia 
---
bool success
